# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='enddate',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='startdate',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
